### ISSUE TITLE
Do we want a spreadsheet comments thing?

### ISSUE THREAD

**Issue by logangbrown** [markhaslam/familysummit.org#3]
On the comments page, there is currently commented out code that contains a text area for submitting comments. I don't know if this is the functionality that Barbara actually wants.

**Comment by markhaslam** [comment]
I can't remember exactly, but I think we talked about possibly using Google Forms and then all the responses could go to a spreadsheet that Barbara can look at and that is tied to Google account we were probably going to create for her.  She may have wanted the comments to go to her email as well? I guess we will need to check with her.

**Comment by logangbrown** [comment]
She just wants it to go to her email
