### ISSUE TITLE
The center workshop and training workshop pages need help

### ISSUE THREAD

**Issue by logangbrown** [markhaslam/familysummit.org#6]
These pages are practically identical, which seems redundant, but they also contain time sensitive information that won't be easy to update in the future. Not to mention they are currently way out of date. We need to figure out if we're going to rework them to contain more general and reusable information, remove one (or both) of them, or maybe include another agenda/calendar object that can be managed though the same account as the other events.

**Comment by markhaslam** [comment]
Very good points. All I could find from Barbara on this is from one of the pages she scanned to us back in December. Below (if it shows up) is just a screen snip of that page she sent us. It definitely doesn't solve this issue and concern though, what she sent is what is on that page currently.

![image](https://cloud.githubusercontent.com/assets/6936232/9459387/2167405c-4ab8-11e5-8ea4-f00aa5c67693.png)

**Comment by logangbrown** [comment]
I've got the updates for these.
