### ISSUE TITLE
There is a link that needs to be added to the volunteer page

### ISSUE THREAD

**Issue by logangbrown** [markhaslam/familysummit.org#7]
There is some text (that is currently red) that indicates a link to a Google docs, or a form, or something for people to use to sign up to volunteer. We need to get a solution for this and then include a link/button.

**Comment by markhaslam** [comment]
The Google form or doc sounds like a good solution if it works for Barbara and isn't confusing for her. If she likes that idea it will be nice because we can use the same Google account that we are probably going to create for her.

**Comment by logangbrown** [comment]
She is just including a phone number and email address here instead.
